name: CI/CD

env:
  DOTNET_VERSION: '8'                 # set this to the .NET Core version to use
  #comes from evironment AZURE_WEBAPP_NAME: 'app-dometrain-github-actions-alx-dev'
on:
  pull_request:
    branches: [ "main" ]
  push:
  workflow_dispatch:

#needed OAuth permissions for Azure
permissions:
    id-token: write
    contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 #checks out what, pull request or main of the repo???

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Test
        run: dotnet test --configuration Release #--no-build

      - name: Publish
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts1
          path: artifacts/

  deploy-dev:
    name: CD Deploy Dev
    needs: build
    #environment: dev #cannot have this 
    uses: ./.github/workflows/step-deploy.yml
    with:
      ENV: dev
    secrets: inherit

  deploy-prod:
    name: CD Deploy Prod
    needs: deploy-dev
    #environment: dev #cannot have this 
    uses: ./.github/workflows/step-deploy.yml
    with:
      ENV: prod
    secrets: inherit
    