name: CI/CD

env:
  DOTNET_VERSION: '8'                 # set this to the .NET Core version to use
  #comes from evironment AZURE_WEBAPP_NAME: 'app-dometrain-github-actions-alx-dev'
on:
  pull_request:
    branches: [ "main" ]
  push:
  workflow_dispatch:

#needed OAuth permissions for Azure
permissions:
    id-token: write
    contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 #checks out what, pull request or main of the repo???

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # - name: Set up dependency caching for faster builds
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.nuget/packages
      #     key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-nuget-
      
      #will build for test anyway
      # - name: Build with dotnet
      #   run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release #--no-build

      - name: Publish
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts1
          path: artifacts/
      

        #     - name: dotnet publish
  #       run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

  #     - name: Upload artifact for deployment job
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: .net-app
  #         path: ${{env.DOTNET_ROOT}}/myapp

  # deploy:
  #   permissions:
  #     contents: none
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Development'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: .net-app

  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy-dev:
    name: CD Deploy Dev
    runs-on: ubuntu-latest
    needs: build
    environment: dev

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts1
          path: artifacts/

      - name: Azure Login
        id: azure-login
        uses: azure/login@v2
        with:
            client-id: ${{secrets.AZURE_CLIENT_ID}}
            tenant-id: ${{secrets.AZURE_TENANT_ID}}
            subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} #not the best way
          package: artifacts/ # ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-prod:
    name: CD Deploy Prod
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: prod

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts1
          path: artifacts/

      - name: Azure Login
        id: azure-login
        uses: azure/login@v2
        with:
            client-id: ${{secrets.AZURE_CLIENT_ID}}
            tenant-id: ${{secrets.AZURE_TENANT_ID}}
            subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} #not the best way
          package: artifacts/ # ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
