name: Step Deploy

on:
  workflow_call: 
    inputs:
        ENV:
            type: string
            required: true
            description: Name (tag) of the environment to deploy to
    secrets:
        AZURE_CLIENT_ID:
            required: true
        AZURE_TENANT_ID:
            required: true
        AZURE_SUBSCRIPTION_ID:
            required: true

#needed OAuth permissions for Azure
permissions:
    id-token: write
    contents: read

jobs:
  deploy:
    name: Deploy ${{ inputs.ENV }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts1
          path: artifacts/

      - name: Azure Login
        id: azure-login
        uses: azure/login@v2
        with:
            client-id: ${{secrets.AZURE_CLIENT_ID}}
            tenant-id: ${{secrets.AZURE_TENANT_ID}}
            subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
            
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          package: artifacts/ 
